---
variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  stage: test
  parallel:
    matrix:
      - BASH_VERSION: ['4.4', '5.0', '5.1', '5.2']
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/bash:${BASH_VERSION}
  before_script:
    - apk add --update-cache make
  script:
    - make test
