---
image:
  name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/debian:bullseye-slim

services:
  - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10-dind
    alias: docker

test4.4:
  stage: test
  image:
    name: gitlab-registry.dubzland.net/holodekk/hbl-testing-image:4.4
  before_script:
    - git submodule init
    - git submodule sync && git submodule update --init
  script:
    - make test
