---
image:
  name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/debian:bullseye-slim

services:
  - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10-dind
    alias: docker

test:
  stage: test
  script:
    - apt update
    - apt install -y make git
    - bash --version
    - git submodule init
    - git submodule update
    - make test
